### ISSUE TITLE
使用fb帳號加入確認鈕在右下方不容易注意到

### ISSUE THREAD

**Issue by lukechang0815** [isuncloud/isuncrowd#48]
https://www.isuncrowd.com/user/signup
選擇join via FB
點擊編輯資料

result
確認鈕在右下方不容易注意到 這是fb原生網頁的問題

**Comment by aryaya** [comment]
右下角有取消确定的按钮：
![image](https://cloud.githubusercontent.com/assets/8801474/8769986/c7e63c9c-2edb-11e5-8e05-d29348ad3692.png)

**Comment by lukechang0815** [comment]
這issue會改成ui的問題 右下角放這麼小的按鈕很難注意到

**Comment by aryaya** [comment]
這個頁面是facebook控制的，外部接口無法控制。
或者讓開發人員再研究一下有沒有其他接口可以調用，不過理論應該是只有這一個了。
