### ISSUE TITLE
選擇join via FB點選上一頁數次回到signup頁面後再點選一次join via FB出現錯誤

### ISSUE THREAD

**Issue by lukechang0815** [isuncloud/isuncrowd#50]
http://test.esangel.com/user/signup
選擇join via FB
點擊編輯資料
點選上一頁數次回到signup頁面
再點選一次join via FB
https://www.facebook.com/dialog/oauth?client_id=828308763913093&redirect_uri=http%3A%2F%2Ftest.esangel.com%2Fsocial%2Fcallback%3Fhauth.done%3Dfacebook&state=e6a02f7c928260f09dec80802cf529c1&scope=email%2Cpublish_stream&display=popup

出現以下錯誤
應用程式的設定不接受這個網址。: 應用程式的設定不接受所提供之一或多個網址。網址必須符合網站網址或畫布（Canvas）應用程式網址；或者，網域必須是應用程式網域的子網域之一。

**Comment by aryaya** [comment]
Luke，你測試的網站是  www.isuncrowd.com還是 test.esangel.com？
請統一使用 www.isuncrowd.com，test那個無法通過域名認證。
