### ISSUE TITLE
新增4個additional docs只出現上面2個

### ISSUE THREAD

**Issue by lukechang0815** [isuncloud/isuncrowd#74]
https://www.isuncrowd.com/invest/investment/46#documents
只有uih32 add2出現
![2015-07-22 12 47 37](https://cloud.githubusercontent.com/assets/11328863/8818137/e53260ce-306f-11e5-8fa4-f659bc72eab6.png)
![2015-07-22 12 47 46](https://cloud.githubusercontent.com/assets/11328863/8818138/e534e92a-306f-11e5-97da-824f723d216f.png)

**Comment by aryaya** [comment]
這個是系統設計需求：
offering document是投資者投資時，出現在第三步document裏面提示用戶仔細閱覽用的。
同issue #71
